[package]
name = "learn-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

rand = "0.9.2"
rayon = "1.7"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9"
toml = "0.7"         # for toml serialization/deserialization
bincode = "2.0.1"               # simple binary format

reqwest = { version = "0.12", features = ["json", "multipart"] }
tokio = { version = "1", features = ["full"] }  # 用于异步

connector = { path = "./connector" }
restaurant = { path = "./restaurant" }